### ISSUE TITLE
super().__init__(daemon=True) 

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#28]
@Justinjay282 

Extend with `daemon=True`, accordingly in `FingerprintThread` and `RFIDThread` like here
https://github.com/Justinjay282/qwerty/blob/8043ec8e633b68056c76dc4d3fb21bebf1220e35/Kiosk_Main.py#L33

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I've committed the changes in `FingerprintThread` and `RFIDThread` I just added the `daemon=True`.Also I searched in SO what does it mean, it will run the thread even if it encountered an exception error? Am I right? somehow it's still confusing to me. Also, I'm having an error in fingerprint scanner it's a hardware issue because of the wiring. even if the program is running when the error occurred it will stop running. To make it work again I have to rerun the program again... Is there a way programmatically to rerun the line above if the exception error occurred?  
```
 try:
            f = PyFingerprint('/dev/ttyUSB0', 57600, 0xFFFFFFFF, 0x00000000)

            if ( f.verifyPassword() == False ):
                raise ValueError('The given fingerprint sensor password is wrong!')
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I've committed the changes in FingerprintThread and RFIDThread I just added the daemon=True.Also I searched in SO what does it mean, it will run the thread even if it encountered an exception error? Am I right? somehow it's still confusing to me

>what does it mean

it's still confusing to me too, as i understand it has changed in Python 3.x to **NOT** hanging the __main__ `Thread` at EXIT while the background `Thread` is stil running.

Is it working for you?
- [ ] Yes
- [ ] No

**Comment by Justinjay282** [comment]
Hi, sir @WK-GiHu, can I ask a question about `tkinter controller`?
