### ISSUE TITLE
Implement method 'def on_fingerprint' in 'class Update_residents'

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#32]
@Justinjay282 

Copy from `FingerprintDevice.__main__` function `def on_fingerprint`.
Before you do so, rename all `fingerprint` to `template` also.

I'm stuck with your logic in `def  Updated_fingerprint`.
- What is list_values[12]?
- Why do you repeat reading two times?
- Why do you have a `else:` and read again?

## Most importand

Can we call **all** three functions after every `f.readImage()` without side effects?
```
f.convertImage(0x01)
f.convertImage(0x02)
f.compareCharacteristics()
```

**Comment by Justinjay282** [comment]
sir, @WK-GiHu 

> @Justinjay282
> 
> Copy from `FingerprintDevice.__main__` function `def on_fingerprint`.
> Before you do so, rename all `fingerprint` to `template` also.
> 
> I'm stuck with your logic in `def Updated_fingerprint`.
> 
> * What is list_values[12]?
> * Why do you repeat reading two times?
> * Why do you have a `else:` and read again?

in `list_values` I get row data of gathered data from the database to treeview.
I get the value of the row selected from treeview using
```
        curItem = self.tree.focus()
        inter_var=self.tree.item(curItem)
        list_values=inter_var['values']
```
the `list_values[12]` is the `FINGERPRINT_TEMPLATE` column value in the database. `if list_values[12] !='':` if true then the's an already registered template for that user, to avoid duplication of finger template, the program will delete the existing template and replace it with a new one for that particular user to register his fingerprint without a duplicate template. the `else:` is if the `list_values[12]` doesn't have a value then the program will not delete the template anymore since there is no template and will proceed to the fingerprint registration without deleting a template. The `if list_values[12] !='':`will deleted the template value to avoid duplication and the `else:` will only for registration if the `list_values[12]` doesn't have a value. Also, the registration is reading the finger two times to compare/check if the user is registering similar fingers

> ## Most importand
> Can we call **all** three functions after every `f.readImage()` without side effects?
> 
> ```
> f.convertImage(0x01)
> f.convertImage(0x02)
> f.compareCharacteristics()
> ```

I tried this with this code
```
 while ( f.readImage() == False ):
        pass

    ## Converts read image to characteristics and stores it in charbuffer 1
    f.convertImage(0x01)
    f.convertImage(0x02)
    f.compareCharacteristics()
```
and I have an error
```
Exception message: The image contains too few feature points
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

>Exception message: 

OK, remove line `f.compareCharacteristics()` and try again.

**Comment by Justinjay282** [comment]
> OK, remove line `f.compareCharacteristics()` and try again.

sir, @WK-GiHu, still got the same error. 
```
Exception message: The image contains too few feature points
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

> still got the same error

OK, we have to divide `0x1` and `0x2`
We need a reference from `class FingerprintDevice`.
I reopen https://github.com/Justinjay282/qwerty/issues/30
