### ISSUE TITLE
Update Kiosk_Main.py and update_resident_fingerprint.py

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#39]
@Justinjay282 

The Pull Request `FingerprintDevice.py` requires changes:

**`Kiosk_Main.py`**:
- [x] Replace to: `self.fp.bind('SEARCH', self.on_fingerprint)`
  https://github.com/Justinjay282/qwerty/blob/ec01893949fb2294fdd7a7b11e706ac03910ff91/Kiosk_Main.py#L130

---

**`update_resident_fingerprint.py`**:

- [x] Remove not longer required
  https://github.com/Justinjay282/qwerty/blob/ec01893949fb2294fdd7a7b11e706ac03910ff91/update_resident_fingerprint.py#L7

- [x] Replace to: `self.app.fp.unbind()`
  https://github.com/Justinjay282/qwerty/blob/ec01893949fb2294fdd7a7b11e706ac03910ff91/update_resident_fingerprint.py#L58

- [x] Replace line 153 to 155
  https://github.com/Justinjay282/qwerty/blob/ec01893949fb2294fdd7a7b11e706ac03910ff91/update_resident_fingerprint.py#L153-L155
  to
  ```
  print('bind REGISTER')
  # bind and set REGISTER mode continue to read fingerprint
  self.app.fp.bind('REGISTER', self.on_fingerprint)
  ```

- [x] Replace line 158 to 161
  https://github.com/Justinjay282/qwerty/blob/ec01893949fb2294fdd7a7b11e706ac03910ff91/update_resident_fingerprint.py#L158-L161
  to
  ```
  print('bind SEARCH')
  # bind and set SEARCH mode continue to read fingerprint
  self.app.fp.bind('SEARCH', self.app.on_fingerprint)
  ```

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I think it's working now. since I've tried it a couple of times and it's really good.
I'll adapt it to `update_admin_fingerprint.py` sir, the only need to change is the database right? I did so and It's working. I'll update all the changes for you to review sir. I updated the `Kiosk_Main.py`, `update_residents_fingerprint.py` and added `update_admin_fingerprint.py`

I'm sorry again if I'm hard to teach, I know you're doing your best to help me and you're doing so much effort not just to help me but also to teach me. After the thesis, I'll take a rest for a week and will study extensively. I'm sorry if I'm hard to teach, I am a working student for 4 yrs and I am not focused on the study especially programming. I resigned a couple of months ago, to focus on my thesis. I just felt like I want to tell some story hehe. Again, sir thank you so much! It looks like not but I've learned so much from you. I actually learned more in you than my adviser/my teacher.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>it's working now. since I've tried it a couple of times and it's really good.
>update all the changes for you to review

Looks OK, well done.
Did  you also running `FingerprintDevice.__main__` to prove it's working?

>the only need to change is the database right?

Didn't understand this, but you may know it better.

>I'll take a rest for a week and will study extensively. 

Read [Don't_repeat_yourself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

**Comment by Justinjay282** [comment]
@WK-GiHu 
> 
> > it's working now. since I've tried it a couple of times and it's really good.
> > update all the changes for you to review
> 
> Looks OK, well done.
> Did you also running `FingerprintDevice.__main__` to prove it's working?
> 
Yes, sir, It's working I just changed the database. I tested it for a couple of times. and it works.
should I change it how it works?

> > the only need to change is the database right?
> 
> Didn't understand this, but you may know it better.
> 
> > I'll take a rest for a week and will study extensively.
> 
> Read [Don't_repeat_yourself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
I read this sir, but I'm quite confused about what it said...

**Comment by WK-GiHu** [comment]
@Justinjay282 

>should I change it how it works? 

No, if it fulfilles your needs stay with it.

>I mean, it's working, it's just the database table it stores is different and the same with login. I hope I encounter no problem here on out. 

Still didn't get ***the database table it stores is different***.
Explain the difference.

**Comment by Justinjay282** [comment]
sir @WK-GiHu 
> Still didn't get _**the database table it stores is different**_.
> Explain the difference.

The overall function of the two modules is the same, the only difference is that the source of the data getting in the table.
In my `update_admin.py` I used this. 
https://github.com/Justinjay282/qwerty/blob/e2330e442a53083d0c51a4f521c4a71f7c6bc8b1/update_admin_fingerprint.py#L116
while in the `update_resident_py` I used this
https://github.com/Justinjay282/qwerty/blob/e2330e442a53083d0c51a4f521c4a71f7c6bc8b1/update_resident_fingerprint.py#L117
but the overall functionality of the two modules is just the same.
Same with my login. I used the table `residents_admin` if the data to be fetched is there, then the admin interface will show. As for the non-admin users, I used the table `residents_db` and so on.
I'm sorry if my way of explaining things is somewhat unclear. I reread my explanation earlier and it's indeed confusing... >.<

> > > Read Don't_repeat_yourself
> > 
> > 
> > I read this sir, but I'm quite confused about what it said...
> 
> Make **DRY** to your own _**principle of software development**_

What I understand here is like don't use the same logic again or don't repeat what you did. not totally "don't repeat" but reduce... somewhat it explains how a person will improve if he thinks of another way to solve a problem? because if a person repetitively uses software patterns I mean he cannot think of any alternative much better solution than he/she used. Is it right? 
It is based on my experience, Before I started programming my mindset is "I just have to know the logic of a certain function or program and I can use it to another one(if I encounter any that can be used that specific logic)" and the **principle of software development** contradicts it and now I know I was totally wrong. I repetitively used **logic patterns** which is a bad principle, although I'm learning it and I thought of a lot of ways on how to deal with my problems. The hardest part for me here are the terms... I am not familiar with the terms using in the programming language that's also one of the reasons why It's hard for me to comprehend lots of programming logic and program. After the thesis, I will go back to 0. I will study from the beginning, I don't think sir if I can be as good as you, I just have to see for myself what future awaits for me. I'll do my best not just for myself but for you as well sir so your effort in teaching will not go to waste. Thank you so much! I hope I can help you someday just like how you help me. Again, sir, Thank you so much! :)

**Comment by WK-GiHu** [comment]
@Justinjay282 

>>the only need to change is the database right?
>
>The overall function of the two modules is the same, the only difference is that the source of the data getting from the database table.

**Now**, i see my wrong interpretation of your above sentence.
I assumed there is a fault by implementation the database access.

OK, all is well

---

>but the overall functionality of the two modules is just the same.

That's a good example of `DRY`!
Instead of copy the whole code, use **one** version and pass the database `residents_db` as a argument.
